//
// Copyright 2025 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: key_transparency.proto

package pb

import (
	pb "github.com/signalapp/keytransparency/tree/transparency/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditRequest comes from a third-party auditor that wishes to sync with the
// latest state of the log.
type AuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_key_transparency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_transparency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_key_transparency_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRequest) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AuditRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// AuditResponse contains the list of new changes to the log.
type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*pb.AuditorUpdate    `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	More          bool                   `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_key_transparency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_transparency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_key_transparency_proto_rawDescGZIP(), []int{1}
}

func (x *AuditResponse) GetUpdates() []*pb.AuditorUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *AuditResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

type TreeSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeSize      uint64                 `protobuf:"varint,1,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeSizeResponse) Reset() {
	*x = TreeSizeResponse{}
	mi := &file_key_transparency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeSizeResponse) ProtoMessage() {}

func (x *TreeSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_transparency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeSizeResponse.ProtoReflect.Descriptor instead.
func (*TreeSizeResponse) Descriptor() ([]byte, []int) {
	return file_key_transparency_proto_rawDescGZIP(), []int{2}
}

func (x *TreeSizeResponse) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

var File_key_transparency_proto protoreflect.FileDescriptor

const file_key_transparency_proto_rawDesc = "" +
	"\n" +
	"\x16key_transparency.proto\x12\x02kt\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12transparency.proto\":\n" +
	"\fAuditRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"Z\n" +
	"\rAuditResponse\x125\n" +
	"\aupdates\x18\x01 \x03(\v2\x1b.transparency.AuditorUpdateR\aupdates\x12\x12\n" +
	"\x04more\x18\x02 \x01(\bR\x04more\"/\n" +
	"\x10TreeSizeResponse\x12\x1b\n" +
	"\ttree_size\x18\x01 \x01(\x04R\btreeSize2\xd6\x01\n" +
	"\x1dKeyTransparencyAuditorService\x12:\n" +
	"\bTreeSize\x12\x16.google.protobuf.Empty\x1a\x14.kt.TreeSizeResponse\"\x00\x12.\n" +
	"\x05Audit\x12\x10.kt.AuditRequest\x1a\x11.kt.AuditResponse\"\x00\x12I\n" +
	"\x0eSetAuditorHead\x12\x1d.transparency.AuditorTreeHead\x1a\x16.google.protobuf.Empty\"\x00B0Z.github.com/signalapp/keytransparency/cmd/kt/pbb\x06proto3"

var (
	file_key_transparency_proto_rawDescOnce sync.Once
	file_key_transparency_proto_rawDescData []byte
)

func file_key_transparency_proto_rawDescGZIP() []byte {
	file_key_transparency_proto_rawDescOnce.Do(func() {
		file_key_transparency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_transparency_proto_rawDesc), len(file_key_transparency_proto_rawDesc)))
	})
	return file_key_transparency_proto_rawDescData
}

var file_key_transparency_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_key_transparency_proto_goTypes = []any{
	(*AuditRequest)(nil),       // 0: kt.AuditRequest
	(*AuditResponse)(nil),      // 1: kt.AuditResponse
	(*TreeSizeResponse)(nil),   // 2: kt.TreeSizeResponse
	(*pb.AuditorUpdate)(nil),   // 3: transparency.AuditorUpdate
	(*emptypb.Empty)(nil),      // 4: google.protobuf.Empty
	(*pb.AuditorTreeHead)(nil), // 5: transparency.AuditorTreeHead
}
var file_key_transparency_proto_depIdxs = []int32{
	3, // 0: kt.AuditResponse.updates:type_name -> transparency.AuditorUpdate
	4, // 1: kt.KeyTransparencyAuditorService.TreeSize:input_type -> google.protobuf.Empty
	0, // 2: kt.KeyTransparencyAuditorService.Audit:input_type -> kt.AuditRequest
	5, // 3: kt.KeyTransparencyAuditorService.SetAuditorHead:input_type -> transparency.AuditorTreeHead
	2, // 4: kt.KeyTransparencyAuditorService.TreeSize:output_type -> kt.TreeSizeResponse
	1, // 5: kt.KeyTransparencyAuditorService.Audit:output_type -> kt.AuditResponse
	4, // 6: kt.KeyTransparencyAuditorService.SetAuditorHead:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_key_transparency_proto_init() }
func file_key_transparency_proto_init() {
	if File_key_transparency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_transparency_proto_rawDesc), len(file_key_transparency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_transparency_proto_goTypes,
		DependencyIndexes: file_key_transparency_proto_depIdxs,
		MessageInfos:      file_key_transparency_proto_msgTypes,
	}.Build()
	File_key_transparency_proto = out.File
	file_key_transparency_proto_goTypes = nil
	file_key_transparency_proto_depIdxs = nil
}
