//
// Copyright 2025 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: key_transparency_test.proto

package pb

import (
	pb "github.com/signalapp/keytransparency/tree/transparency/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_key_transparency_test_proto protoreflect.FileDescriptor

const file_key_transparency_test_proto_rawDesc = "" +
	"\n" +
	"\x1bkey_transparency_test.proto\x12\akt_test\x1a\x12transparency.proto2c\n" +
	"\x1aKeyTransparencyTestService\x12E\n" +
	"\x06Update\x12\x1b.transparency.UpdateRequest\x1a\x1c.transparency.UpdateResponse\"\x00B5Z3github.com/signalapp/keytransparency/cmd/kt-test/pbb\x06proto3"

var file_key_transparency_test_proto_goTypes = []any{
	(*pb.UpdateRequest)(nil),  // 0: transparency.UpdateRequest
	(*pb.UpdateResponse)(nil), // 1: transparency.UpdateResponse
}
var file_key_transparency_test_proto_depIdxs = []int32{
	0, // 0: kt_test.KeyTransparencyTestService.Update:input_type -> transparency.UpdateRequest
	1, // 1: kt_test.KeyTransparencyTestService.Update:output_type -> transparency.UpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_transparency_test_proto_init() }
func file_key_transparency_test_proto_init() {
	if File_key_transparency_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_transparency_test_proto_rawDesc), len(file_key_transparency_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_transparency_test_proto_goTypes,
		DependencyIndexes: file_key_transparency_test_proto_depIdxs,
	}.Build()
	File_key_transparency_test_proto = out.File
	file_key_transparency_test_proto_goTypes = nil
	file_key_transparency_test_proto_depIdxs = nil
}
