//
// Copyright 2025 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: key_transparency.proto

package pb

import (
	context "context"
	pb "github.com/signalapp/keytransparency/tree/transparency/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyTransparencyAuditorService_TreeSize_FullMethodName       = "/kt.KeyTransparencyAuditorService/TreeSize"
	KeyTransparencyAuditorService_Audit_FullMethodName          = "/kt.KeyTransparencyAuditorService/Audit"
	KeyTransparencyAuditorService_SetAuditorHead_FullMethodName = "/kt.KeyTransparencyAuditorService/SetAuditorHead"
)

// KeyTransparencyAuditorServiceClient is the client API for KeyTransparencyAuditorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A key transparency service used to provide data to auditors and to accept auditor-signed tree heads.
// Outside of third-party auditors, this service's endpoints are *not* intended to be used by external clients.
// It is exposed to the public internet by necessity but will reject calls from unauthenticated callers.
type KeyTransparencyAuditorServiceClient interface {
	// Auditors can query this endpoint to learn the current size of the transparency log.
	TreeSize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TreeSizeResponse, error)
	// Auditors use this endpoint to request a batch of key transparency service updates to audit.
	Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error)
	// Auditors use this endpoint to return a signature on the log tree root hash corresponding to the last audited update.
	SetAuditorHead(ctx context.Context, in *pb.AuditorTreeHead, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type keyTransparencyAuditorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyTransparencyAuditorServiceClient(cc grpc.ClientConnInterface) KeyTransparencyAuditorServiceClient {
	return &keyTransparencyAuditorServiceClient{cc}
}

func (c *keyTransparencyAuditorServiceClient) TreeSize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TreeSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeSizeResponse)
	err := c.cc.Invoke(ctx, KeyTransparencyAuditorService_TreeSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyAuditorServiceClient) Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, KeyTransparencyAuditorService_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyTransparencyAuditorServiceClient) SetAuditorHead(ctx context.Context, in *pb.AuditorTreeHead, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KeyTransparencyAuditorService_SetAuditorHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyTransparencyAuditorServiceServer is the server API for KeyTransparencyAuditorService service.
// All implementations must embed UnimplementedKeyTransparencyAuditorServiceServer
// for forward compatibility.
//
// A key transparency service used to provide data to auditors and to accept auditor-signed tree heads.
// Outside of third-party auditors, this service's endpoints are *not* intended to be used by external clients.
// It is exposed to the public internet by necessity but will reject calls from unauthenticated callers.
type KeyTransparencyAuditorServiceServer interface {
	// Auditors can query this endpoint to learn the current size of the transparency log.
	TreeSize(context.Context, *emptypb.Empty) (*TreeSizeResponse, error)
	// Auditors use this endpoint to request a batch of key transparency service updates to audit.
	Audit(context.Context, *AuditRequest) (*AuditResponse, error)
	// Auditors use this endpoint to return a signature on the log tree root hash corresponding to the last audited update.
	SetAuditorHead(context.Context, *pb.AuditorTreeHead) (*emptypb.Empty, error)
	mustEmbedUnimplementedKeyTransparencyAuditorServiceServer()
}

// UnimplementedKeyTransparencyAuditorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyTransparencyAuditorServiceServer struct{}

func (UnimplementedKeyTransparencyAuditorServiceServer) TreeSize(context.Context, *emptypb.Empty) (*TreeSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TreeSize not implemented")
}
func (UnimplementedKeyTransparencyAuditorServiceServer) Audit(context.Context, *AuditRequest) (*AuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedKeyTransparencyAuditorServiceServer) SetAuditorHead(context.Context, *pb.AuditorTreeHead) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAuditorHead not implemented")
}
func (UnimplementedKeyTransparencyAuditorServiceServer) mustEmbedUnimplementedKeyTransparencyAuditorServiceServer() {
}
func (UnimplementedKeyTransparencyAuditorServiceServer) testEmbeddedByValue() {}

// UnsafeKeyTransparencyAuditorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyTransparencyAuditorServiceServer will
// result in compilation errors.
type UnsafeKeyTransparencyAuditorServiceServer interface {
	mustEmbedUnimplementedKeyTransparencyAuditorServiceServer()
}

func RegisterKeyTransparencyAuditorServiceServer(s grpc.ServiceRegistrar, srv KeyTransparencyAuditorServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyTransparencyAuditorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyTransparencyAuditorService_ServiceDesc, srv)
}

func _KeyTransparencyAuditorService_TreeSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAuditorServiceServer).TreeSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyTransparencyAuditorService_TreeSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAuditorServiceServer).TreeSize(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyAuditorService_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAuditorServiceServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyTransparencyAuditorService_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAuditorServiceServer).Audit(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyTransparencyAuditorService_SetAuditorHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.AuditorTreeHead)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyTransparencyAuditorServiceServer).SetAuditorHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyTransparencyAuditorService_SetAuditorHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyTransparencyAuditorServiceServer).SetAuditorHead(ctx, req.(*pb.AuditorTreeHead))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyTransparencyAuditorService_ServiceDesc is the grpc.ServiceDesc for KeyTransparencyAuditorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyTransparencyAuditorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kt.KeyTransparencyAuditorService",
	HandlerType: (*KeyTransparencyAuditorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TreeSize",
			Handler:    _KeyTransparencyAuditorService_TreeSize_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _KeyTransparencyAuditorService_Audit_Handler,
		},
		{
			MethodName: "SetAuditorHead",
			Handler:    _KeyTransparencyAuditorService_SetAuditorHead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "key_transparency.proto",
}
