name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod

      - name: Build Go
        run: go build ./...

      - name: Test Go
        run: go test ./...

      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: 'temurin'
          java-version-file: ./filter-key-updates/.java-version
          cache: 'maven'

      - name: Build and test Java
        run: ./mvnw verify
        working-directory: filter-key-updates
