name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Build Go
        run: go build ./...

      - name: Test Go
        run: go test ./...

      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: 'temurin'
          java-version-file: ./filter-key-updates/.java-version
          cache: 'maven'

      - name: Build and test Java
        run: ./mvnw verify
        working-directory: filter-key-updates
