name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Build Go
        run: go build ./...

      - name: Test Go
        run: go test ./...

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version-file: ./filter-key-updates/.java-version
          cache: 'maven'

      - name: Build and test Java
        run: ./mvnw verify
        working-directory: filter-key-updates
